name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build sdist
      run: make sdist

    - name: archive artifacts
      uses: actions/upload-artifacts@v3
      path: |
        dist
